// actions Projeto

export const EXIBIR_FORMULARIO_PROJETO = 'EXIBIR_FORMULARIO_PROJETO';
export const GET_PROJETOS = 'GET_PROJETOS';
export const ADICIONAR_PROJETO = 'ADICIONAR_PROJETO';
export const SET_ERRO_FORMULARIO_PROJETO = 'SET_ERRO_FORMULARIO_PROJETO';
export const SELECIONAR_PROJETO = 'SELECIONAR_PROJETO';
export const EXCLUIR_PROJETO = 'EXCLUIR_PROJETO';
export const ERRO_STATUS_PROJETO = 'ERRO_STATUS_PROJETO';

// actions Tarefas

export const GET_TAREFAS_PROJETO = 'GET_TAREFAS_PROJETO';
export const ADICIONAR_TAREFA = 'ADICIONAR_TAREFA';
export const SET_ERRO_FORMULARIO_TAREFA = 'SET_ERRO_FORMULARIO_TAREFA';
export const EXCLUIR_TAREFA = 'EXCLUIR_TAREFA';
export const SELECIONAR_TAREFA = 'SELECIONAR_TAREFA';
export const EDITAR_DADOS_TAREFA = 'EDITAR_DADOS_TAREFA';
export const ERRO_STATUS_TAREFA = 'ERRO_STATUS_TAREFA';

// actions Alertas

export const EXIBIR_ALERTAS = 'EXIBIR_ALERTAS';
export const OCULTAR_ALERTAS = 'OCULTAR_ALERTAS';

// actions Autenticacao

export const REGISTRADO_COM_SUCESSO = 'REGISTRADO_COM_SUCESSO';
export const ERRO_AO_REGISTRAR = 'ERRO_AO_REGISTRAR';
export const GET_USUARIO = 'GET_USUARIO';
export const LOGIN_COM_SUCESSO = 'LOGIN_COM_SUCESSO';
export const ERRO_LOGIN = 'ERRO_LOGIN';
export const ENCERRAR_SESSAO = 'ENCERRAR_SESSAO';
